baseURL = 'https://fliqqs.github.io/'
languageCode = 'en-us'
title = 'fliqqs'
theme = "console"

[params]
    customCSS = ["css/custom.css"]

[permalinks]
    headless = "/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true